name: C/C++ CI

on: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install valgrind
      run: sudo apt-get install -y valgrind
    - name: install du
      run: sudo apt-get install -y du
    - name: make
      run: make
    - name: make test
      run: make test